trigger:
  branches:
    include:
      - master
  tags:
    include:
      - 'v*'
  paths:
    exclude:
      - '*.md'
pr: 
  branches:
    include:
      - master
  paths:
    exclude:
      - '*.md'

jobs:
  - job: Build
    steps:
      - task: Npm@1
        displayName: Install Deps
        inputs:
          command: custom
          customCommand: ci

      - bash: npm run lint
        displayName: Lint

      - bash: npm run build
        displayName: Build
        failOnStderr: true

      - bash: npm run test
        displayName: Test

      - bash: npm prune --production
        displayName: Streamline Build

      - task: Npm@1
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
        inputs:
          command: publish
          publishPackageMetadata: true
          publishEndpoint: jrc356 - npm registry